### ISSUE TITLE
Unable to pip install curlify 

### ISSUE THREAD

**Issue by yaara1000** [ofw/curlify#20]
Hi,
I tried pip installing the package today and got the following error:
```
Collecting shlex>="3" (from curlify)
  ERROR: Could not find a version that satisfies the requirement shlex>="3" (from curlify) (from versions: none)
ERROR: No matching distribution found for shlex>="3" (from curlify)
```
I'm using python 2.7
Looks like this was committed just a few hours ago,
Any idea? 

Thank you

**Comment by korenhadar** [comment]
Hi,
I'm using python 3.6 and having the same issue since 5 hours from now (last commit)
```
Collecting shlex>="3" (from curlify>=2.1.0->facebook-business==3.2.8)
ERROR: Could not find a version that satisfies the requirement shlex>="3" (from curlify>=2.1.0->facebook-business==3.2.8)
No matching distribution found for shlex>="3" (from curlify>=2.1.0->facebook-business==3.2.8)
```
Thank you!

**Comment by MatthiasReinholz** [comment]
Same here on Python 3.7.4.
I was able to work-around with
`pip install curlify==2.1.1`

**Comment by tewner** [comment]
Same here. Going to hard-code 2.1.1 for now.

**Comment by Nicolas-Masson-Wizaplace** [comment]
A regression with my recent PR, the fix in another https://github.com/ofw/curlify/pull/21

**Comment by ofw** [comment]
Fixed.
