### ISSUE TITLE
Empty `-d ''` option confuses Postman

### ISSUE THREAD

**Issue by HappyEinara** [ofw/curlify#6]
Many of my collaborators use Postman, which can import cURL commands. Using curlify to send a request from my debugger to them to reproduce is very useful.

However, curlify generates empty `-d ''` options which appear to be unnecessary (e.g. for a plain GET request). Postman fails to import these unedited commands with an (admittedly nonsensical) error: `Error while importing Curl: 0 option-less arguments found. Only one is supported (the URL)`

Postman should in my opinion tolerate this better, however I doubt the `-d ''` is semantically necessary for curlify to generate.

Could you consider removing any options that result in an empty string from the output?

**Comment by ofw** [comment]
Thanks, sounds legit. Fixed!
