### ISSUE TITLE
data not encoded correctly in Python 3

### ISSUE THREAD

**Issue by hmoffatt** [ofw/curlify#9]
I have the following test script:

```
#!/usr/bin/env python3
import requests, curlify

data = {'foo':'bar'}
url = 'https://httpbin.org/post'

r = requests.post(url, json=data, headers={})

print(r.request)
print(curlify.to_curl(r.request))
```

This is generating:

`curl -X 'POST' -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 14' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.19.1' -d 'b'{"foo": "bar"}'' 'https://httpbin.org/post'`

Note the 'b' before the data (Python for a byte string). This makes it an invalid shell command.

**Comment by ofw** [comment]
Thanks, fixed it!
